{% set name = "cuda-sanitizer-api" %}
{% set version = "13.4.57" %}
{% set cuda_version = "13.4" %}
{% set platform = "linux-x86_64" %}  # [linux64]
{% set platform = "linux-ppc64le" %}  # [ppc64le]
{% set platform = "linux-sbsa" %}  # [aarch64]
{% set platform = "windows-x86_64" %}  # [win64]
{% set platform = "windows-arm64" %}  # [win and arm64]
{% set extension = "tar.xz" %}  # [not win]
{% set extension = "zip" %}  # [win]
{% set exists = "which" %}  # [not win]
{% set exists = "where" %}  # [win]
{% set sha256 = "443465d4dcb77f45a2eb2c9adf2d1e0d7b4d0966ce84acf6d89b4c555bd55f5b" %}  # [linux64]
{% set sha256 = "275928dee0c2c61316a61faeb7a2930de60a986e005b7d1c25e861a4ecb9fd13" %}  # [aarch64]
{% set sha256 = "8a1af222f79e3ee1a6539dc9d59825685e0361f03a752fc50ab62a8e34fd9a77" %}  # [win64]
{% set sha256 = "39fea12b65c9a17932f680fa6245d3cbf5fb8fb78665becd3357c924b6956d60" %}  # [win and arm64]

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://developer.download.nvidia.com/compute/cuda/redist/cuda_sanitizer_api/{{ platform }}/cuda_sanitizer_api-{{ platform }}-{{ version }}-archive.{{ extension }}
  sha256: {{ sha256 }}

build:
  number: 0
  binary_relocation: false
  skip: true  # [osx or ppc64le]
  missing_dso_whitelist:
    - '$RPATH/libInterceptorInjectionTarget.so'  # [linux]
    - '$RPATH/InterceptorInjectionTarget.dll'    # [win]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
    - arm-variant * {{ arm_variant_type }}  # [aarch64]
    - patchelf <0.18.0                      # [linux]
    - cf-nvidia-tools 1  # [linux]
  host:
    - cuda-version {{ cuda_version }}
  run:
    - {{ pin_compatible("cuda-version", max_pin="x.x") }}
  run_constrained:
    - arm-variant * {{ arm_variant_type }}  # [aarch64]

test:
  requires:
    - patchelf       # [linux]
  files:
    - test-rpath.sh  # [linux]
  commands:
    - test -f $PREFIX/bin/compute-sanitizer                                         # [linux]
    - test -f $PREFIX/compute-sanitizer/compute-sanitizer                           # [linux]
    - if not exist %LIBRARY_PREFIX%\compute-sanitizer\compute-sanitizer.exe exit 1  # [win]
    - if not exist %PREFIX%\Scripts\compute-sanitizer.bat exit 1                    # [win]
    - bash test-rpath.sh                                                            # [linux]
    - {{ exists }} compute-sanitizer
    - compute-sanitizer --version                                                   # [build_platform == target_platform]

about:
  home: https://docs.nvidia.com/compute-sanitizer/SanitizerApiGuide/index.html
  license_file: LICENSE
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: Provides a set of APIs to enable third party tools to write GPU sanitizing tools
  description: |
    Provides a set of APIs to enable third-party tools to write GPU sanitizing
    tools, such as memory and race checkers.
  doc_url: https://docs.nvidia.com/compute-sanitizer/SanitizerApiGuide/index.html

extra:
  recipe-maintainers:
    - conda-forge/cuda
